name: gamepads_web
description: "A new Flutter plugin project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  gamepads_platform_interface:
    path: ../gamepads_platform_interface
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: gamepads
    platforms:
      web:
        pluginClass: GamepadsWebPlugin
        fileName: gamepads_web.dart

#flutter:
#  plugin:
#    platforms:
#      web:
#        pluginClass: GamepadsWebWeb
#        fileName: gamepads_web_web.dart

